a.exe:User.cpp Mediator.cpp Dress.cpp main.cpp
	g++ -W -Wall -std=c++11 -g User.cpp Mediator.cpp Dress.cpp main.cpp
	./a.exe
	rm a.exe
e:User.cpp Mediator.cpp Dress.cpp main.cpp
	g++ -W -Wall -std=c++11 -g User.cpp Mediator.cpp Dress.cpp main.cpp
	./a.exe < in > out
	rm a.exe
clean:
	rm a.exe